# Site settings
title: More Pablo
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/pablo/" # the subpath of your site, e.g. /blog/
url: "https://www.saurya.com/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
